# Generated by Django 4.1.1 on 2022-09-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fliq', '0005_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
